ignore:
  - "/*"
  - "C:/*"
  - "C:/*"
  - "C:\\*"
  - "../*"
  - "*/.cargo/*"
  - "*\\.cargo\\*"
  - "*\\.cargo\\*"
branch: true
ignore-not-existing: true
llvm: true
filter: covered
output-type: lcov
