on:
  push:
    paths:
      - '.github/workflows/security_audit.yml' # Run when this workflow changes
      - '**/Cargo.toml' # Run when dependencies change
      - '**/Cargo.lock' # Run when dependencies change
  pull_request:
    paths:
      - '.github/workflows/security_audit.yml' # Run when this workflow changes
      - '**/Cargo.toml' # Run when dependencies change
      - '**/Cargo.lock' # Run when dependencies change
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Run periodically to capture recent developments
  workflow_dispatch: # Run when manually triggered
  workflow_call: # Run when called by another workflow

name: 🕵️‍♂️ Security Audit Workflow

jobs:
  audit_job:
    name: 🕵️‍♂️ Security Audit Job
    strategy:
      fail-fast: false
      matrix:
        platform: [linux, windows, apple]
        cpu_architecture: [x86_64]
        include:
          - platform: linux
            cicd_runner: ubuntu-latest
          - platform: windows
            cicd_runner: windows-latest
          - platform: apple
            cicd_runner: macos-latest
          - compilation_target: x86_64-unknown-linux-gnu
            cpu_architecture: x86_64
            platform: linux
            toolchain: gnu
          - compilation_target: x86_64-pc-windows-msvc
            cpu_architecture: x86_64
            platform: windows
            toolchain: msvc
          - compilation_target: x86_64-apple-darwin
            cpu_architecture: x86_64
            platform: apple
            toolchain: darwin
    permissions:
      contents: read
      issues: write
    runs-on: ${{ matrix.cicd_runner }}
    steps:
      - name: 🎟 Checkout Git Repository Step
        id: repository_checkout_step
        uses: actions/checkout@v4
      - name: 🐍 Setup Python Step
        id: python_setup_step
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 
          cache: 'pip'
      - name: ↕️ Install Dependencies Step
        id: dependencies_install_step
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: 🗂 Setup Cache Step
        id: cache_setup_step
        uses: Swatinem/rust-cache@v2
      - name: 🕵️‍♂️ Security Audit Step
        id: audit_step
        uses: actions-rust-lang/audit@v1
      