on:
  push:
    paths:
      - '.github/workflows/security_audit.yml' # Run when this workflow changes
      - '**/Cargo.toml' # Run when dependencies change
      - '**/Cargo.lock' # Run when dependencies change
  schedule:
    - cron: '0 0 * * *' # Run periodically to capture recent developments
  workflow_dispatch: # Run when manually triggered
  workflow_call: # Run when called by another workflow

name: 🕵️‍♂️ Security Audit

jobs:
  audit:
    name: 🕵️‍♂️ Security Audit Job
    runs-on: ubuntu-latest
    steps:
      - name: 🎟 Checkout Git Repository Step
        id: repository_checkout_step
        uses: actions/checkout@v4
      - name: 🕵️‍♂️ Security Audit Step
        id: audit_step
        uses: actions-rust-lang/audit@v1
